### ISSUE TITLE
Unable to download the binaries mentioned in the documentation

### ISSUE THREAD

**Issue by rapatchi** [microsoft/go#1084]
I have tried downloading the binary distribution i am getting the following error.

URL: https://aka.ms/golang/release/latest/go1.21.linux-arm64.tar.gz

Error:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>InvalidAuthenticationInfo</Code>
<Message>Authentication information is not given in the correct format. Check the value of Authorization header. RequestId:fec52bc2-901e-009e-34a5-1c6c81000000 Time:2023-11-21T18:03:21.2816105Z</Message>
</Error>

**Comment by dagood** [comment]
Thanks for reporting this!

Currently it's working for me. What happens if you try to directly access the URL it redirects to, https://dotnetbuildoutput.blob.core.windows.net/golang/microsoft/release-branch.go1.21/20231107.2/go.20231107.2.linux-arm64.tar.gz ?

I'm accessing the URL from the US. I wonder if it's an issue with georeplication or aka.ms. We haven't updated this URL recently, so I would expect it to be stable.

**Comment by rapatchi** [comment]
Looks like the issue is with my browser i was able to dowload it using wget.
