### ISSUE TITLE
`go tool cover` doesn't work with FIPS mode enabled on Mariner 2.0

### ISSUE THREAD

**Issue by olishenton** [microsoft/go#1253]
The Go runtime/coverage library uses an MD5 hash in its metadata calculations ([code for reference](https://cs.opensource.google/go/go/+/refs/tags/go1.22.4:src/runtime/coverage/emit.go;l=214)). 
The "vendor crypto backends" patch moves this to use `EVP_DigestInit_ex` on a fresh evp ctx when using OpenSSL as the backend ([code for reference](https://github.com/microsoft/go/blob/microsoft/main/patches/0006-Vendor-crypto-backends.patch#L3034)).

On Mariner 2.0, use of md5 is is explicitly disabled in FIPS mode ([code for reference](https://github.com/microsoft/azurelinux/blob/2.0/SPECS/openssl/openssl-1.1.1-fips.patch#L896)) unless `EVP_MD_CTX_FLAG_NON_FIPS_ALLOW` is set on the evp ctx.

Resultant stack trace:
```
panic: EVP_DigestInit_ex
openssl error(s):
error:060800C8:digital envelope routines:EVP_DigestInit_ex:disabled for FIPS
	crypto/evp/digest.c:135

goroutine 1 [running]:
vendor/github.com/golang-fips/openssl/v2.newEvpHash(0x2, 0x10, 0x40)
	/usr/local/go/src/vendor/github.com/golang-fips/openssl/v2/hash.go:132 +0x12e
vendor/github.com/golang-fips/openssl/v2.NewMD5(...)
	/usr/local/go/src/vendor/github.com/golang-fips/openssl/v2/hash.go:248
crypto/internal/backend.NewMD5(...)
	/usr/local/go/src/crypto/internal/backend/openssl_linux.go:135
crypto/md5.New()
	/usr/local/go/src/crypto/md5/md5.go:104 +0x3a
runtime/coverage.prepareForMetaEmit()
	/usr/local/go/src/runtime/coverage/emit.go:214 +0x197
```

Of course, this isn't that big a deal, since code coverage behaviour with FIPS mode disabled should be the same as if enabled, but it would be nice if this worked.

I don't remember what the FIPS implementations are like on other distros' OpenSSL releases, but wouldn't be surprised if this is a more general problem. Also worth remarking that Mariner 3.0 will move to using SymCrypt as the provider for FIPS mode which will heavily change this picture - in all expecting this Issue to be a LiveWith.

**Comment by dagood** [comment]
Interesting, it seems to me the Microsoft Go OpenSSL backend should *always* pass `EVP_MD_CTX_FLAG_NON_FIPS_ALLOW` in order to meet our current compatibility goals, because there's no API that existing apps are already using to indicate when non-FIPS algorithms should be usable.

Of course, each app must be reviewed for FIPS compliance, but the goal of Microsoft Go is that if it is determined that the use is compliant, no source change is required for it to build and run successfully.

Yeah, other distros of FIPS-compliant Go that I've seen don't go for total compat *and* total OpenSSL usage, and this kind of `panic` might even be considered desirable. We use OpenSSL in more places than might be considered necessary (in order to follow a Microsoft internal policy), and we allow non-FIPS usage of algorithms while using the OpenSSL backend for compat reasons.

@microsoft/golang-compiler

---

> The "vendor crypto backends" patch moves this to use `EVP_DigestInit_ex` on a fresh evp ctx

The phrasing doesn't seem like the way I'd describe it, so pointing out a few things in case you didn't realize: the vendoring patch is just grabbing the source for https://github.com/golang-fips/openssl. The backend foundation patch wires up the md5 packages to use a backend (if selected): https://github.com/microsoft/go/blob/035727a366d2759706ef90343b733b6782db917f/patches/0002-Add-crypto-backend-foundation.patch#L883-L885

And the OpenSSL backend patch wires them together: https://github.com/microsoft/go/blob/035727a366d2759706ef90343b733b6782db917f/patches/0004-Add-OpenSSL-crypto-backend.patch#L332

**Comment by qmuntal** [comment]
> Interesting, it seems to me the Microsoft Go OpenSSL backend should always pass EVP_MD_CTX_FLAG_NON_FIPS_ALLOW in order to meet our current compatibility goals

That's true for OpenSSL 1, but `EVP_MD_CTX_FLAG_NON_FIPS_ALLOW` doesn't exist in OpenSSL 3. We should instead pass the `?fips` property when calling [EVP_MD_fetch](https://docs.openssl.org/3.3/man3/EVP_MD_fetch/) so that the OpenSSL provider selection mechanism can fall back to a non-fips implementation even when the default properties are `fips=true`. See https://github.com/openssl/openssl/discussions/24643 for more context.

Also, Red Hat might not want to have this behavior enabled by default in the golang-fips/openssl module (they are normally more strict about falling back to Go crypto), so we probably should gate this behind a global variable which we would always set in our toolchain.

**Comment by xnox** [comment]
> That's true for OpenSSL 1, but `EVP_MD_CTX_FLAG_NON_FIPS_ALLOW` doesn't exist in OpenSSL 3. We should instead pass the `?fips` property when calling [EVP_MD_fetch](https://docs.openssl.org/3.3/man3/EVP_MD_fetch/) so that the OpenSSL provider selection mechanism can fall back to a non-fips implementation even when the default properties are `fips=true`. See [openssl/openssl#24643](https://github.com/openssl/openssl/discussions/24643) for more context.

and when one does request for "fips=no" algorithm, one may also need to load the default provider. See https://github.com/python/cpython/pull/118236/files

**Comment by xnox** [comment]
Another option, is to vendor in gocrypto md5 implementation into coverage, as it is currently required to build coverage. And consider that it is using that for non-security purposes.

I've tried to add new APIs to go/crypto to force fallback/bypass, but it does not seem to be trivial to do so.

As ideally there would be a new module I don't know "math/md5" or a context that one can pass to Sum() and New() to get access to md5 for non-security purposes. Still not well versed on how to add new modules and features, as bootstrap build always fails whenever I try to extend things.

Also separately I guess it is worth filing upstream issue to consider upgrading coverage away from md5, in the next revision format.

Or we can force the format change ourselves, and upgrade coverage to truncated sha256 to md5 size.

**Comment by xnox** [comment]
Actually vendoring vanilla crypto/md5 into internal/coverage/md5 is quite easy, and it makes coverage just work. I think. Checking stuff, and will propose a patch if it all works.

**Comment by qmuntal** [comment]
Fixed by https://github.com/golang-fips/openssl/pull/199 and https://go-review.googlesource.com/c/go/+/617360.
