### ISSUE TITLE
go-images/1.22-fips-bookworm: go CLI reports using StandardCrypto?

### ISSUE THREAD

**Issue by kaovilai** [microsoft/go#1412]
```
docker run -it --rm --platform=linux/arm64 -e GOEXPERIMENT=boringcrypto mcr.microsoft.com/oss/go/microsoft/golang:1.22-fips-bookworm sh -c 'go tool nm $(which go) | grep crypto/internal/boring && go env'
  1ec1f0 T crypto/internal/boring/sig.StandardCrypto.abi0
```

Perhaps I'm missing something :)

<details><summary>Docker & OS Details</summary>
<p>

```
❯ docker version
Client: Docker Engine - Community
 Version:           27.1.1
 API version:       1.41 (downgraded from 1.46)
 Go version:        go1.22.5
 Git commit:        63125853e3
 Built:             Fri Jul 19 17:35:01 2024
 OS/Arch:           darwin/arm64
 Context:           default

Server: linux/arm64/rhcos-4.17
 Podman Engine:
  Version:          5.2.3
  APIVersion:       5.2.3
  Arch:             arm64
  BuildTime:        2024-10-07T07:47:17Z
  Experimental:     false
  GitCommit:        
  GoVersion:        go1.22.5 (Red Hat 1.22.5-1.el9)
  KernelVersion:    5.14.0-427.40.1.el9_4.aarch64
  MinAPIVersion:    4.0.0
  Os:               linux
 Conmon:
  Version:          conmon version 2.1.12, commit: 9b3f2e7d010b1b512d88609d3a7b9a913bbaf1e0
  Package:          conmon-2.1.12-4.rhaos4.17.el9.aarch64
 OCI Runtime (crun):
  Version:          crun version 1.17
commit: 000fa0d4eeed8938301f3bcf8206405315bc1017
rundir: /run/crun
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  Package:          crun-1.17-1.rhaos4.17.el9.aarch64
 Engine:
  Version:          5.2.3
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.22.5 (Red Hat 1.22.5-1.el9)
  Git commit:       
  Built:            Mon Oct  7 07:47:17 2024
  OS/Arch:          linux/arm64
  Experimental:     false

❯ sw_vers 
ProductName:            macOS
ProductVersion:         14.7.1
BuildVersion:           23H222
```

</p>
</details>

**Comment by kaovilai** [comment]
```
❯ docker run --rm -it registry.access.redhat.com/ubi9/go-toolset sh -c 'go tool nm $(which go) | grep "crypto/internal/boring/sig."'
  5dd980 t crypto/internal/boring/sig.BoringCrypto.abi0
```

[Red Hat toolset images](https://catalog.redhat.com/software/containers/ubi9/go-toolset/61e5c00b4ec9945c18787690?q=go+&architecture=amd64&image=673b06b060835d24815e760f&container-tabs=gti&gti-tabs=registry-tokens) worked.

**Comment by dagood** [comment]
Hi there! This command is inspecting the Go compiler/toolset itself:

```
go tool nm $(which go)
```

We don't produce a FIPS compliant Go toolset, we only make a Go toolset that is capable of producing FIPS compliant Go apps. Some people may need to run a Go toolset in FIPS mode (e.g. to compile a Go app on a FIPS compliant machine), but we haven't found a need for that at Microsoft, so we haven't targeted that. You might want to take a look at https://github.com/microsoft/go/issues/1221#issuecomment-2351535374 if that's what you're looking for.

That said, the check also sets `GOEXPERIMENT=boringcrypto`, which has no effect in this situation because nothing's being compiled, so I might not have the right idea of what that check is actually trying to determine.

As a side note, we do generally preserve the behavior of `GOEXPERIMENT=boringcrypto`, but we don't claim to properly support it. This repo is really about `GOEXPERIMENT=systemcrypto` and the underlying `opensslcrypto` and `cngcrypto`. https://github.com/microsoft/go/tree/microsoft/main/eng/doc/fips#usage-build

**Comment by kaovilai** [comment]
> We don't produce a FIPS compliant Go toolset

Thanks for clarifying.

> we only make a Go toolset that is capable of producing FIPS compliant Go apps.

good to know.
